### ISSUE TITLE
CentOSでデプロイが出来ません

### ISSUE THREAD

**Issue by Rmtram** [kohkimakimoto/altax#46]
こんにちは
シンプルで扱いやすい為、いつもaltaxを利用させていただいております。

早速ですが、当方の仮想環境でSSHで接続する際に、
PHPSecLibのMath/BigIntegerにてoffsetエラーが発生しておりデプロイができません。
(Net_SSH2でBigIntegerを利用しており、そこでこけています)
altaxに同梱されているMath/BigIntegerのバージョンが0.3.9以前でしたら、
今回のバグが発生する可能性が高いので、外部パッケージのアップデートを
して頂きたくチケットを出しました。

またStackOverflowに今回と似た様な症状が投稿されていましたので、
記載させていただきます。
http://stackoverflow.com/questions/26704186/phpseclib-running-on-php5-5

Error report.

```
Notice: Undefined offset: 1724 in phar:///path/to/
altax.phar/vendor/phpseclib/phpseclib/phpseclib/Math                                                                                                                          /BigInteger.php on line 1078

Notice: Undefined offset: 1725 in phar:///path/to/
altax.phar/vendor/phpseclib/phpseclib/phpseclib/Math                                                                                                                          /BigInteger.php on line 1078

Notice: Undefined offset: 1726 in phar:///path/to/
altax.phar/vendor/phpseclib/phpseclib/phpseclib/Math                                                                                                                     /BigInteger.php on line 1078

.........
```

OS.

```
CentOS release 6.6 (Final)
```

PHP version.

```
5.5.30 
```

Altax version

```
3.0.14
```

**Comment by kohkimakimoto** [comment]
すみません。まだ解決してないのにCloseしてしまいました。

**Comment by kohkimakimoto** [comment]
@Rmtram 私の方ですぐにお問い合わせのバグを再現できる環境がないのですが、ご提案のとおりphpseclibのバージョンをアップデートしたものでv3.0.15として更新しました。
これでご確認いただけますでしょうか？

**Comment by Rmtram** [comment]
無事正常に動作確認ができました！
迅速にご対応していただき、誠にありがとうございます。
今後もどうぞよろしくお願い申し上げます。
